from __future__ import annotations

from pathlib import Path
from typing import Iterable


def _read_lines(path: Path) -> list[str]:
    return Path(path).read_text(encoding="utf-8", errors="ignore").splitlines()


def _sort_satellites(satellites: Iterable[str]) -> list[str]:
    return sorted(set(satellites), key=lambda s: (s[0], int(s[1:])))


def _make_satellite_lines(satellites: list[str]) -> list[str]:
    """
    Create 5 SP3-c-like '+' satellite list lines.
    RTKLIB 2.4.2 p13 reads the number of satellites from a 2-character field,
    therefore this compatibility file must keep ns <= 99.
    """
    ns = len(satellites)

    if ns > 99:
        raise ValueError(
            f"RTKLIB 2.4.2-compatible SP3 subset must have <= 99 satellites; got {ns}."
        )

    chunks = [satellites[i:i + 17] for i in range(0, len(satellites), 17)]
    lines = []

    for idx in range(5):
        chunk = chunks[idx] if idx < len(chunks) else []

        if idx == 0:
            line = f"+  {ns:3d}   " + "".join(chunk)
        else:
            line = "+        " + "".join(chunk)

        lines.append(line)

    return lines


def _make_accuracy_lines(ns: int) -> list[str]:
    """
    Create 5 SP3-c-like '++' accuracy lines.
    Values are inherited as generic placeholders for compatibility.
    """
    vals = ["  5"] * ns
    chunks = [vals[i:i + 17] for i in range(0, len(vals), 17)]
    lines = []

    for idx in range(5):
        chunk = chunks[idx] if idx < len(chunks) else []
        line = "++       " + "".join(chunk)
        lines.append(line)

    return lines


def convert_sp3_to_rtklib_242_subset(
    input_sp3: str | Path,
    output_dir: str | Path,
    systems: tuple[str, ...] = ("G", "E"),
    output_name: str | None = None,
) -> Path:
    """
    Convert a modern multi-GNSS SP3-d file to an RTKLIB 2.4.2 p13-compatible
    SP3-c-like subset.

    Default systems:
        G = GPS
        E = Galileo

    Purpose:
        RTKLIB 2.4.2 p13 has limited SP3-c-era parsing assumptions.
        Modern MGEX SP3-d files with >99 satellites can fail silently
        as precise ephemeris input.
    """
    input_sp3 = Path(input_sp3).expanduser()
    output_dir = Path(output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not input_sp3.exists():
        raise FileNotFoundError(input_sp3)

    lines = _read_lines(input_sp3)

    if len(lines) < 30:
        raise ValueError(f"SP3 file appears too short: {input_sp3}")

    if not lines[0].startswith("#"):
        raise ValueError(f"Invalid SP3 first line: {lines[0]!r}")

    allowed_systems = tuple(s.upper() for s in systems)

    satellites = []
    for line in lines:
        if line.startswith("P") and len(line) >= 4:
            sat = line[1:4]
            if sat[0] in allowed_systems:
                satellites.append(sat)

    satellites = _sort_satellites(satellites)

    if not satellites:
        raise ValueError(
            f"No satellite records found for systems={allowed_systems} in {input_sp3}"
        )

    if len(satellites) > 99:
        raise ValueError(
            f"Selected systems={allowed_systems} give {len(satellites)} satellites. "
            "Reduce systems so ns <= 99 for RTKLIB 2.4.2 p13 compatibility."
        )

    if output_name is None:
        suffix = "".join(allowed_systems).lower()
        output_name = input_sp3.stem.lower() + f"_{suffix}_rtklib242.sp3"

    output_sp3 = output_dir / output_name

    header = []
    header.append("#c" + lines[0][2:])
    header.append(lines[1])
    header.extend(_make_satellite_lines(satellites))
    header.extend(_make_accuracy_lines(len(satellites)))
    header.append("%c M  cc GPS ccc cccc cccc cccc cccc ccccc ccccc ccccc ccccc")
    header.append("%c cc cc ccc ccc cccc cccc cccc cccc ccccc ccccc ccccc ccccc")
    header.append("%f  1.2500000  1.025000000  0.00000000000  0.000000000000000")
    header.append("%f  0.0000000  0.000000000  0.00000000000  0.000000000000000")
    header.append("%i    0    0    0    0      0      0      0      0         0")
    header.append("%i    0    0    0    0      0      0      0      0         0")
    header.append("/* RTKLIB 2.4.2-compatible SP3-c-like subset")
    header.append(f"/* Original source: {input_sp3.name}")
    header.append(f"/* Systems retained: {','.join(allowed_systems)}")
    header.append("/* Generated by RTKLIB Baseline Orchestrator sp3_compat.py")

    if len(header) != 22:
        raise RuntimeError(f"Internal SP3 header length error: {len(header)} != 22")

    selected = set(satellites)

    body = []
    for line in lines:
        if line.startswith("*"):
            body.append(line)
        elif line.startswith("P") and line[1:4] in selected:
            body.append(line)
        elif line.startswith("EOF"):
            body.append(line)

    output_sp3.write_text("\n".join(header + body) + "\n", encoding="utf-8")

    return output_sp3
